kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            requests:
              memory: "100Mi"
              cpu: "128"
            limits:
              memory: "200Mi"
              cpu: "256"      
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_DATABASE
              value: "satyam"

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Mi