kind: CronJob
apiVersion: batch/v1
metadata:
  name: nginx-cron
  namespace: nginx
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: minute-backup
          labels:
            app: minute-backup
        spec:
          containers:
          - name: backup
            image: busybox:latest
            command: ["sh", "-c", "echo Hello this is a cron job! && sleep 10"]
          restartPolicy: OnFailure
