kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc 
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Mi
  storageClassName: ""    
  volumeName: nginx-pv
