kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: satyam120/my-custom:1.1
          #image: satyam120/nginx_app:latest
          #command: ["python"]
          #args: ["manage.py", "runserver", "0.0.0.0:3000"]
          ports:
            - containerPort: 80

